# Generated by Django 5.2.5 on 2025-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_booking_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_name',
            field=models.CharField(default='Guest', max_length=100),
        ),
    ]
